red_polymers = [
    "Acetophenone/Oxymethylene Copolymer",
    "Acetylenediurea/Formaldehyde/Tosylamide Crosspolymer",
    "Acrolein/Acrylic Acid Copolymer",
    "Acrylamide/Ammonium Acrylate Copolymer",
    "Acrylamide/Ethalkonium Chloride Acrylate Copolymer",
    "Acrylamide/Ethyltrimonium Chloride Acrylate/Ethalkonium Chloride",
    "Acrylate Copolymer",
    "Acrylamide/Sodium Acrylate Copolymer",
    "Acrylamide/Sodium Acryloyldimethyltaurate Copolymer",
    "Acrylamide/Sodium Acryloyldimethyltaurate/Acrylic Acid Copolymer",
    "Acrylamides/DMAPA Acrylates/Methoxy PEG Methacrylate Copolymer",
    "Acrylamidopropyltrimonium Chloride/Acrylates Copolymer",
    "Acrylates Copolymer",
    "Acrylates Crosspolymer",
    "Acrylates Crosspolymer-3",
    "Acrylates Crosspolymer-4",
    "Acrylates/Acetoacetoxyethyl Methacrylate Copolymer",
    "Acrylates/Acrylamide Copolymer",
    "Acrylates/Aminoacrylates/C10-30 Alkyl PEG-20 Itaconate Copolymer",
    "Acrylates/Ammonium Methacrylate Copolymer",
    "Acrylates/Beheneth-25 Methacrylate Copolymer",
    "Acrylates/Beheneth-25 Methacrylate/Steareth-30 Methacrylate Copolymer",
    "Acrylates/Behenyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Behenyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Bis-Hydroxypropyl Dimethicone Crosspolymer",
]

red_polymers.extend([
    "Acrylates/C1-2 Succinates/Hydroxyacrylates Copolymer",
    "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    "Acrylates/C10-30 Alkyl Methacrylate Copolymer",
    "Acrylates/C12-13 Alkyl Methacrylates/Methoxyethyl Acrylate Crosspolymer",
    "Acrylates/C12-22 Alkyl Methacrylate Copolymer",
    "Acrylates/C26-29 Olefin Copolymer",
    "Acrylates/C5-8 Alkyl Acrylate Copolymer",
    "Acrylates/Carbamate Copolymer",
    "Acrylates/Ceteareth-20 Methacrylate Crosspolymer",
    "Acrylates/Ceteareth-25 Methacrylate/Methacrylamide Crosspolymer",
    "Acrylates/Ceteth-20 Itaconate Copolymer",
    "Acrylates/Ceteth-20 Methacrylate Copolymer",
    "Acrylates/Diacetoneacrylamide Copolymer",
    "Acrylates/Diethylaminoethyl Methacrylate/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Dimethicone Copolymer",
    "Acrylates/Dimethicone Methacrylate Copolymer",
    "Acrylates/Dimethicone Methacrylate/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Dimethiconol Acrylate Copolymer",
    "Acrylates/Dimethylaminoethyl Methacrylate Copolymer",
    "Acrylates/Ethylamine Oxide Methacrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate Crosspolymer",
    "Acrylates/Ethylhexyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Glycidyl Methacrylate Crosspolymer",
    "Acrylates/Ethylhexyl Acrylate/Hema Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Hema/Styrene Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Styrene Copolymer",
    "Acrylates/Ethylhexylacrylamide Copolymer",
    "Acrylates/Hydroxyesters Acrylates Copolymer",
    "Acrylates/Hydroxyethyl Acrylate/Lauryl Acrylate Copolymer",
    "Acrylates/Hydroxyethyl Acrylate/Methoxyethyl Acrylate Copolymer",
    "Acrylates/Laureth-25 Methacrylate Copolymer",
    "Acrylates/Lauryl Acrylate/Stearyl Acrylate/Ethylamine Oxide Methacrylate Copolymer"
])

red_polymers.extend([
    "Acrylates/Lauryl Methacrylate Copolymer",
    "Acrylates/Lauryl Methacrylate/Tridecyl Methacrylate Crosspolymer",
    "Acrylates/Methacrylamide Copolymer",
    "Acrylates/Methoxy PEG-15 Methacrylate Copolymer",
    "Acrylates/Methoxy PEG-23 Methacrylate Copolymer",
    "Acrylates/Methoxy PEG-23 Methacrylate/Perfluorootyl Ethyl Acrylate Copolymer",
    "Acrylates/Methoxy PEG-4 Methacrylate Copolymer",
    "Acrylates/Octylacrylamide Copolymer",
    "Acrylates/Octylacrylamide/Diphenyl Amodimethicone Copolymer",
    "Acrylates/Palmeth-25 Acrylate Copolymer",
    "Acrylates/Palmeth-25 Itaconate Copolymer",
    "Acrylates/PEG-10 Maleate/Styrene Copolymer",
    "Acrylates/PEG-4 Dimethacrylate Crosspolymer",
    "Acrylates/Polytrimethylsiloxymethacrylate Copolymer",
    "Acrylates/Propyl Trimethicone Methacrylate Copolymer",
    "Acrylates/Rhus Verniciflua Sap Extract Crosspolymer",
    "Acrylates/Steareth-20 Itaconate Copolymer",
    "Acrylates/Steareth-20 Methacrylate Copolymer",
    "Acrylates/Steareth-20 Methacrylate Crosspolymer",
    "Acrylates/Steareth-30 Methacrylate Copolymer",
    "Acrylates/Steareth-50 Acrylate Copolymer",
    "Acrylates/Stearyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Stearyl Acrylate/Ethylamine Oxide Methacrylate Copolymer",
    "Acrylates/Stearyl Methacrylate Copolymer",
    "Acrylates/T-Butylacrylamide Copolymer",
    "Acrylates/TDI/Trimethylolpropane Copolymer",
    "Acrylates/Tridecyl Acrylate/Triethoxysilylpropyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Trifluoropropylmethacrylate/Polytrimethyl Siloxymethacrylate Copolymer",
    "Acrylates/Tris(Trimethylsiloxy)Silylpropyl Methacrylate Copolymer",
    "Acrylates/VA Copolymer",
    "Acrylates/VA Crosspolymer"
])

red_polymers.extend([
    "Acrylates/Vinyl Isodecanoate Crosspolymer",
    "Acrylates/Vinyl Neodecanoate Crosspolymer",
    "Acrylates/VP Copolymer",
    "Acrylates/VP/Dimethylaminoethyl Methacrylate/Diacetone",
    "Acrylamide/Hydroxypropyl Acrylate Copolymer",
    "Acrylic Acid/Acrylamidomethyl Propane Sulfonic Acid Copolymer",
    "Acrylic Acid/Acrylonitrogens Copolymer",
    "Acrylic Acid/C12-22 Alkyl Acrylate Copolymer",
    "Acrylic Acid/Isobornyl Methacrylate/Isobutyl Methacrylate Copolymer",
    "Acrylic Acid/Isobutyl Acrylate/Isobornyl Acrylate Copolymer",
    "Acrylic Acid/Phosphorylcholine Glycol Acrylate Crosspolymer",
    "Acrylic Acid/Stearyl Acrylate Copolymer",
    "Acrylic Acid/Stearyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylonitrile/Butadiene/Styrene Copolymer",
    "Acrylonitrile/Glycol Dimethacrylate Crosspolymer",
    "Acrylonitrile/Methacrylonitrile/Methyl Methacrylate Copolymer",
    "Acrylonitrile/Methyl Methacrylate/Vinylidene Chloride Copolymer",
    "Acryloyl Dimethyl Taurate/Melamine/PEG-Methacrylate Crosspolymer",
    "Acryloyl Dimethyl Taurate/Melamine/PEG-6 Methacrylate/Phloroglucinol Crosspolymer",
    "Allyl Methacrylate/Glycol Dimethacryate Crosspolymer",
    "Allyl Methacrylates Crosspolymer",
    "Allyl Stearate/VA Copolymer",
    "Aminoethylacrylate Phosphate/Acrylates Copolymer",
    "Aminoethylpropanediol-Acrylates/Acrylamide Copolymer",
    "Aminoethylpropanediol-Ampd-Acrylates/Diacetoneacrylamide Copolymer",
    "Ammonium Acrylates Copolymer",
    "Ammonium Acrylates/Acrylonitrogens Copolymer",
    "Ammonium Acrylates/Ethylhexyl Acrylate Copolymer",
    "Ammonium Acrylates/Methyl Styrene/Styrene Copolymer",
    "Ammonium Acryloyl Dimethyltaurate/Carboxyethyl Acrylate Crosspolymer",
    "Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer",
    "Ammonium Acryloyldimethyltaurate/Laureth-7 Methacrylate Copolymer",
    "Ammonium Acryloyldimethyltaurate/Steareth-25 Methacrylate"
])

red_polymers.extend([
    "Ammonium Acryloyldimethyltaurate/Steareth-8 Methacrylate Copolymer",
    "Ammonium Acryloydimethyltaurate/Vinyl Formamide Copolymer",
    "Ammonium Polyacrylate",
    "Ammonium Styrene/Acrylates Copolymer",
    "Ammonium Styrene/Acrylates/Ethylhexyl Acrylate/Lauryl Acrylate Copolymer",
    "Ammonium VA/Acrylates Copolymer",
    "AMP-Acrylate/C1-18 Alkyl Acrylates/C1-8 Alkyl Acrylamide Copolymer",
    "AMP-Acrylates Copolymer",
    "AMP-Acrylates/Allyl Methacrylate Copolymer",
    "AMP-Acrylates/C1-18 Alkyl Acrylate/C1-8 Alkyl Acrylamide Copolymer",
    "Acrylamide/Hydroxyethylacrylate Copolymer",
    "AMP-Acrylates/Diacetoneacrylamide Copolymer",
    "AMP-Acrylates/Dimethylaminoethylmethacrylate Copolymer",
    "AMP-Acrylates/Ethylhexyl Acrylate Copolymer",
    "AMPD-Acrylates/Diacetoneacrylamide Copolymer",
    "Behenyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Behenyl Methacrylate/Ethylamine Oxide Methacrylate Copolymer",
    "Behenyl Methacrylate/Perfluorooctylethyl Methacrylate Copolymer",
    "Behenyl Methacrylate/T-Butyl Methacrylate Copolymer",
    "Bis-Hydroxyethyl Acrylate Poly(Neopentyl Glycol Adipate)/Ipdi Copolymer",
    "Bis-Hydroxyethyl Acrylate Polyneopentyl Glycol Adipate/Tdi Copolymer",
    "Bis-Hydroxypropylmethacrylate Poly(1,4-Butanediol)-9/Ipdi Copolymer",
    "Bis-Pentaerythrityl Diacrylate/Ipdi Copolymer",
    "Bis-Vinyl Diphenyl Dimethicone",
    "Bis-Vinyldimethicone Crosspolymer",
    "Butene/Propylene Copolymer",
    "Butyl Acrylate/C6-14 Perfluoroalkylethyl Acrylate/Mercaptopropyl Dimethicone Copolymer",
    "Butyl Acrylate/Cyclohexyl Methacrylate Copolymer",
    "Butyl Acrylate/Ethylhexyl Methacrylate Copolymer",
    "Butyl Acrylate/Ethyltrimonium Chloride Methacrylate/Styrene Copolymer",
    "Butyl Acrylate/Glycol Dimethacrylate Crosspolymer"
])

red_polymers.extend([
    "Butyl Acrylate/Hydroxyethyl Methacrylate Copolymer",
    "Butyl Acrylate/Hydroxypropyl Dimethicone Acrylate Copolymer",
    "Butyl Acrylate/Isopropylacrylamide/PEG-18 Dimethacrylate Crosspolymer",
    "Butyl Acrylate/Styrene Copolymer",
    "Butyl Benzoic Acid/Phthalic Anhydride/Trimethylolethane Copolymer",
    "Butyl Dimethicone Acrylate/Cyclohexylmethacrylate/Ethylhexyl Acrylate Copolymer",
    "Butyl Ester Of Ethylene/MA Copolymer",
    "Butyl Ester Of PVM/MA Copolymer",
    "Butyl Methacrylate/DMAPA Acrylates/Vinylacetamide Crosspolymer",
    "Butyl Polydimethylsiloxyl Ethylene/Propylene/Vinylnorbornene Copolymer",
    "Butylaminoethyl Methacrylate Crosspolymer",
    "Butyldimethicone Methacrylate/Methyl Methacrylate Crosspolymer",
    "Butylene/Ethylene Copolymer",
    "Butylene/Ethylene/Propylene Copolymer",
    "Butylene/Ethylene/Styrene Copolymer",
    "C12-22 Alkyl Acrylate/Hydroxyethylacrylate Copolymer",
    "C18-22 Alkyl PEG-25 Methacrylate/Diethylaminoethyl Methacrylate Copolymer",
    "C20-24 Olefin/Oleyl Alcohol Copolymer",
    "C26-28 Alkyldimethylsilyl Polypropylsilsesquioxane",
    "C30-38 Olefin/Isopropyl Maleate/MA Copolymer",
    "C4-6 Olefin/Styrene Copolymer",
    "C6-14 Perfluoroalkylethyl Acrylate/Hema Copolymer",
    "C8-22 Alkyl Acrylate/Butyl Dimethicone Methacrylate Copolymer",
    "C8-22 Alkyl Acrylates/Methacrylic Acid Crosspolymer",
    "Carbomer",
    "Carbomer 940",
    "Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer",
    "Cetyl Dimethicone",
    "Cetyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Cetyl Hexacosyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Corn Starch/Acrylamide/Sodium Acrylate Copolymer"
])

red_polymers.extend([
    "Crotonic Acid/Vinyl C8-12 Isoalkyl Esters/VA/Bis-Vinyldimethicone Crosspolymer",
    "Cyclohexyl Methacrylate/Ethylhexyl Methacrylate Copolymer",
    "Dea-Styrene/Acrylates/DVB Copolymer",
    "Dicyclopentadiene/Isopentene/Isoprene/Styrene Copolymer",
    "Diethylaminoethyl Methacrylate/Hema/Perfluorohexylethyl Methacrylate Crosspolymer",
    "Dimethicone",
    "Dimethicone Crosspolymer",
    "Dimethyl Acrylamide/Hydroxyethyl Acrylate/Methoxyethyl Acrylate Copolymer",
    "Dimethylacrylamide/Acrylic Acid/Polystyrene Ethyl Methacrylate Copolymer",
    "Dimethylacrylamide/Ethyltrimonium Chloride Methacrylate Copolymer",
    "Dimethylaminoethylmethacrylate/Hema/Lauryl Methacrylate Copolymer",
    "Divinyldimethicone/Dimethicone Copolymer",
    "Divinyldimethicone/Dimethicone Crosspolymer",
    "DMAPA Acrylates/Acrylic Acid/Acrylonitrogens Copolymer",
    "DVP/Isobornyl Methacrylate/Lauryl Methacrylate Copolymer",
    "Ethalkonium Chloride Acrylate/Hema/Styrene Copolymer",
    "Ethylene Vinyl Acetate Copolymer",
    "Ethylene Vinyl Alcohol Copolymer (EVOH)",
    "Ethylene/Acrylate(s) Copolymer",
    "Ethylene/Acrylic Acid Copolymer",
    "Ethylene/Acrylic Acid/VA Copolymer",
    "Ethylene/Calcium Acrylate Copolymer",
    "Ethylene/Ethylidene Norbornene/Propylene Copolymer",
    "Ethylene/MA Copolymer",
    "Ethylene/Magnesium Acrylate Copolymer",
    "Ethylene/Maleic Anhydride/Propylene Copolymer",
    "Ethylene/Methacrylate Copolymer",
    "Ethylene/Methylacrylate Copolymer",
    "Ethylene/Octene Copolymer",
    "Ethylene/Potassium Acrylate Copolymer",
    "Ethylene/Propylene Copolymer"
])

red_polymers.extend([
    "Ethylene/Propylene/Styrene Copolymer",
    "Ethylene/Sodium Acrylate Copolymer",
    "Ethylene/Sodium Sulfoisophthalate/Terephthalate Copolymer",
    "Ethylene/VA Copolymer",
    "Ethylene/Zinc Acrylate Copolymer",
    "Ethylenediamine/Dimer Tallate Copolymer Bis-Hydrogenated Tallow Amide",
    "Ethylenediamine/Hydrogenated Dimer Dilinoleate Copolymer Bis-Di-C14-18 Alkyl Amide",
    "Ethylenediamine/Stearyl Dimer Dilinoleate Copolymer",
    "Ethylenediamine/Stearyl Dimer Tallate Copolymer",
    "Ethylhexyl Acrylate/Methyl Methacrylate Copolymer",
    "Ethylhexyl Acrylate/VP/Dimethicone Methacrylate Copolymer",
    "Fibroin/PEG-16/Sodium Acrylate Copolymer",
    "Glyceryl Acrylate/Acrylic Acid Copolymer",
    "Glyceryl Polyacrylate",
    "Glyceryl Polymethacrylate",
    "Glycerylamidoethyl Methacrylate/Stearyl Methacrylate Copolymer",
    "Glycol Dimethacrylate Crosspolymer",
    "Glycol Dimethacrylate/Vinyl Alcohol Crosspolymer",
    "Hexafluoropropylene/Tetrafluoroethylene Copolymer",
    "Hydrogenated Butadiene/Isoprene/Styrene Copolymer",
    "Hydrogenated Butylene/Ethylene/Styrene Copolymer",
    "Hydrogenated Dicyclopentadiene/Isopentene/Isoprene/Styrene Copolymer",
    "Hydrogenated Ethylene/Propylene/Styrene Copolymer",
    "Hydrogenated Styrene/Butadiene Copolymer",
    "Hydrogenated Styrene/Isoprene Copolymer",
    "Hydrogenated Styrene/Methyl Styrene/Indene Copolymer",
    "Hydrolyzed Ethylene/MA Copolymer",
    "Hydrolyzed VA/Vinyl Acetoacetate Copolymer",
    "Hydroxyethyl Acrylate/LPDI/PPG-15 Glyceryl Ether Copolymer",
    "Hydroxyethyl Acrylate/Methoxyethyl Acrylate Copolymer",
    "Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer",
    "Hydroxyethyl/Methoxyethyl Acrylate Copolymer",
    "Hydroxyethyl/Methoxyethyl Acrylate/Butyl Acrylate Copolymer"
])

red_polymers.extend([
    "Hydroxyethylcellulose/Phosphorylcholine Glycol Acrylate Copolymer",
    "Hydroxypropyl Dimethiconylpropyl Acrylates Copolymer",
    "Isobutyl Methacrylate/Trifluoroethylmethacrylate/Bis-Hydroxypropyl Dimethicone Acrylate Copolymer",
    "Isobutylene/Isoprene Copolymer",
    "Isobutylene/MA Copolymer",
    "Isobutylene/Sodium Maleate Copolymer",
    "Isobutylene/Styrene Copolymer",
    "Isobutylmethacrylate/Bis-Hydroxypropyl Dimethicone Acrylate Copolymer",
    "Isobutylmethacrylate/Trifluoroethylmethacrylate/Bis-Hydroxypropyl Dimethicone Acrylate Copolymer",
    "Isopropylidenediphenyl Bisoxyhydroxypropyl Methacrylate/TMDI Copolymer",
    "Lauryl Acrylate Crosspolymer",
    "Lauryl Acrylate/VA Copolymer",
    "Lauryl Acrylate/VA Crosspolymer",
    "Lauryl Methacrylate/Glycol Dimethacrylate Copolymer",
    "Lauryl Methacrylate/Glycol Dimethacrylate Crosspolymer",
    "Lauryl Methacrylate/Sodium Methacrylate Crosspolymer",
    "Lauryl Polydimethylsiloxyethyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Maleated Hexene/Propylene Copolymer",
    "Methacrylic Acid/Styrene/VP Copolymer",
    "Methacryloyl Ethyl Betaine/Acrylates Copolymer",
    "Methyl Acrylate/Methylene Drometrizole Methacrylate Copolymer",
    "Methyl Methacrylate Crosspolymer",
    "Methyl Methacrylate Crosspolymer-2",
    "Methyl Methacrylate/Acrylonitrile Copolymer",
    "Methyl Methacrylate/Ethylhexyl Acrylate/Butyl Dimethicone Propyl Methacrylate Copolymer",
    "Methyl Methacrylate/Glycol Dimethacrylate Crosspolymer",
    "Methyl Methacrylate/PEG/PPG-4/3 Methacrylate Crosspolymer",
    "Methyl Methacrylate/Trimethoxysilylpropyl Methacrylate Crosspolymer",
    "Methylbutene/Methylstyrene/Piperylene Copolymer",
    "Methylstyrene/Vinyltoluene Copolymer"
])

red_polymers.extend([
    "Nylon",
    "Nylon 12",
    "Nylon 6/12",
    "Nylon-10/10",
    "Nylon-11",
    "Nylon-12",
    "Nylon-12 Fluorescent Brightener 230 Salt",
    "Nylon-6",
    "Nylon-66",
    "Octylacrylamide/Acrylates/Butylaminoethyl Methacrylate Copolymer",
    "Oxidized Polyethylene",
    "Oxidized Polypropylene",
    "PEG-800/Polyvinyl Alcohol Copolymer",
    "PEG/PPG-25/25 Dimethicone/Acrylates Copolymer",
    "PEG/PPG-5/2 Methacrylate/Methacrylic Acid Crosspolymer",
    "PEG/PPG/Butylene/Dimethicone Copolymer",
    "PEGoterate",
    "Phenol/Styrene/Methylstyrene Copolymer",
    "Poly (E-Caprolactone)",
    "Poly C10-30 Alkyl Acrylate",
    "Poly-P-Phenylene Terephthalamide",
    "Poly(Methoxy PEG-9 Methacrylate)",
    "Poly[Oxymethylene Melamine Acrylates/Acrylamide]",
    "Polyacrylamide",
    "Polyacrylate",
    "Polyacrylate Crosspolymer-11",
    "Polyacrylate Crosspolymer-3",
    "Polyacrylate Crosspolymer-4",
    "Polyacrylate Crosspolymer-5",
    "Polyacrylate Crosspolymer-6",
    "Polyacrylate Crosspolymer-7",
    "Polyacrylate Crosspolymer-8"
])

red_polymers.extend([
    "Polyacrylate-1",
    "Polyacrylate-1 Crosspolymer",
    "Polyacrylate-10",
    "Polyacrylate-11",
    "Polyacrylate-12",
    "Polyacrylate-13",
    "Polyacrylate-14",
    "Polyacrylate-15",
    "Polyacrylate-16",
    "Polyacrylate-17",
    "Polyacrylate-18",
    "Polyacrylate-19",
    "Polyacrylate-2",
    "Polyacrylate-2 Crosspolymer",
    "Polyacrylate-21",
    "Polyacrylate-22",
    "Polyacrylate-24",
    "Polyacrylate-25",
    "Polyacrylate-26",
    "Polyacrylate-27",
    "Polyacrylate-28",
    "Polyacrylate-29",
    "Polyacrylate-3",
    "Polyacrylate-30",
    "Polyacrylate-31",
    "Polyacrylate-32",
    "Polyacrylate-33",
    "Polyacrylate-4",
    "Polyacrylate-5",
    "Polyacrylate-6",
    "Polyacrylate-7",
    "Polyacrylate-8",
    "Polyacrylate-9",
    "Polyacrylic acid"
])

red_polymers.extend([
    "Polyacrylonitrile",
    "Polyalkyl Stereate/Vinyl Acetate Copolymers",
    "Polyamide-1",
    "Polyamide-2",
    "Polyamide-5",
    "Polyamide-8",
    "Polybutene",
    "Polybutyl acrylate",
    "Polybutyl methacrylate",
    "Polybutylene Terephthalate (PBT)",
    "Polycaprolactam (Nylon 6)",
    "Polychlorotrifluoroethylene",
    "Polydimethylaminoethyl Methacrylate",
    "Polydimethylsiloxane (silicone)",
    "Polyester-1",
    "Polyester-11",
    "Polyester-23",
    "Polyester-27",
    "Polyester-3",
    "Polyester-4",
    "Polyester-5",
    "Polyester-7",
    "Polyester-8",
    "Polyethyl acrylate",
    "Polyethylene (PE)",
    "Polyethylene Isoterephthalate (PET)",
    "Polyethylene Naphthalate",
    "Polyethylene Terephthalate (PET)",
    "Polyethylene/Isopropyl Maleate/MA Copolyol",
    "Polyethylene/Polyethylene Terephthalate Laminated Powder",
    "Polyethylene/Polypentaerythrityl Terephthalate Laminated Powder",
    "Polyethylhexyl Acrylate",
    "Polyethylhexyl Methacrylate",
    "Polyethylmethacrylate"
])

red_polymers.extend([
    "Polyhydroxyethylmethacrylate",
    "Polyimide-1",
    "Polyisobornyl acrylate",
    "Polyisobutene",
    "Polyisobutyl methacrylate",
    "Polyisobutylene",
    "Polyisoprene",
    "Polylactic Acid",
    "Polylaurolactam (Nylon 12 or Amide-12)",
    "Polymethyl Acrylate (PMA)",
    "Polymethyl Methacrylate",
    "Polymethyl Methacrylate (PMMA)",
    "Polymethyl Methacrylate/Polypentaerythrityl Terephthalate/Stearate/Palmitate Laminated Powder",
    "Polymethylsilsesquioxane",
    "Polymethylsilsesquioxane/Trimethylsiloxysilicate",
    "Polypentaerythrityl terephthalate",
    "Polypropyl acrylate",
    "Polypropyl methacrylate (PPMA)",
    "Polypropylene (PP)",
    "Polypropylene Oxide (Polypropylene Glycol)",
    "Polypropylene Terephthalate (PPT)",
    "Polyquaternium-6",
    "Polyquaternium-7",
    "Polysilicone-11",
    "Polysilicone-15",
    "Polysilicone-18",
    "Polysilicone-2",
    "Polysilicone-8"
])

red_polymers.extend([
    "Polysilicone-9",
    "Polystearyl methacrylate",
    "Polystyrene",
    "Polystyrene/Acrylate copolymer",
    "Polystyrene/Hydrogenated Polyisopentene Copolymer",
    "Polytetrafluoroethylene (PTFE) (Teflon)",
    "Polytetrafluoroethylene Acetoxypropyl Betaine",
    "Polytrimethylsiloxysilicate (Silicone resin)",
    "Polyurethane",
    "Polyurethane Crosspolymer-2",
    "Polyurethane-1",
    "Polyurethane-10",
    "Polyurethane-11",
    "Polyurethane-12",
    "Polyurethane-13",
    "Polyurethane-14",
    "Polyurethane-15",
    "Polyurethane-16",
    "Polyurethane-17",
    "Polyurethane-2",
    "Polyurethane-20",
    "Polyurethane-21",
    "Polyurethane-23",
    "Polyurethane-24",
    "Polyurethane-24/Methyl Methacrylate Crosspolymer",
    "Polyurethane-25",
    "Polyurethane-26",
    "Polyurethane-27",
    "Polyurethane-28",
    "Polyurethane-29",
    "Polyurethane-32",
    "Polyurethane-33",
    "Polyurethane-33",
    "Polyurethane-34"
])

red_polymers.extend([
    "Polyurethane-35",
    "Polyurethane-36",
    "Polyurethane-39",
    "Polyurethane-4",
    "Polyurethane-40",
    "Polyurethane-41",
    "Polyurethane-42",
    "Polyurethane-43",
    "Polyurethane-44",
    "Polyurethane-45",
    "Polyurethane-46",
    "Polyurethane-47",
    "Polyurethane-48",
    "Polyurethane-5",
    "Polyurethane-51",
    "Polyurethane-52",
    "Polyurethane-53",
    "Polyurethane-6",
    "Polyurethane-62",
    "Polyurethane-64",
    "Polyurethane-7",
    "Polyurethane-79",
    "Polyurethane-8",
    "Polyurethane-9",
    "Polyvidone",
    "Polyvinyl acetate",
    "Polyvinyl Alcohol (PVA)",
    "Polyvinyl Butyral",
    "Polyvinyl chloride",
    "Polyvinyl Imidazolinium Acetate",
    "Polyvinyl Isobutyl Ether",
    "Polyvinyl Laurate",
    "Polyvinyl Methyl Ether"
])

red_polymers.extend([
    "Polyvinyl Stearyl Ether",
    "Polyvinylacetal Diethylaminoacetate",
    "Polyvinylacetamide",
    "Polyvinylalcohol Crosspolymer",
    "Polyvinylcaprolactam",
    "Polyvinylformamide",
    "Polyvinylidene chloride",
    "Polyvinylidene Difluoride",
    "Polyvinylpyrrolidone",
    "Polyvinylpyrrolidone (PVP)",
    "Potassium Acrylates Copolymer",
    "Potassium Acrylates/Acrylamide Copolymer",
    "Potassium Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    "Potassium Acrylates/Ethylhexyl Acrylate Copolymer",
    "Potassium Aluminum Polyacrylate",
    "Potassium Polyacrylate",
    "Povidone",
    "Propyl Trimethicone Methacrylate Crosspolymer",
    "PVP",
    "PVP/VA/Vinyl Propionate Copolymer",
    "Sodium Acrylate/Acrylonitrogens Copolymer",
    "Sodium Acrylate/Acryloyldimethyltaurate/Dimethylacrylamide Crosspolymer",
    "Sodium Acrylate/Hydroxyethyl Acrylamide Copolymer",
    "Sodium Acrylate/Sodium Acrylamidomethylpropane Sulfonate Copolymer",
    "Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer",
    "Sodium Acrylate/Sodium Acryloyldimethyl Taurate/Acrylamide Copolymer",
    "Sodium Acrylate/Vinyl Alcohol Copolymer",
    "Sodium Acrylate/Vinylacetamide Copolymer",
    "Sodium Acrylates Copolymer",
    "Sodium Acrylates Crosspolymer",
    "Sodium Acrylates Crosspolymer-2",
    "Sodium Acrylates/Acrolein Copolymer"
])

red_polymers.extend([
    "Sodium Acrylates/Beheneth-25 Methacrylate Crosspolymer",
    "Sodium Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    "Sodium Acrylates/Ethylhexyl Acrylate Copolymer",
    "Sodium Acrylates/Vinyl Isodecanoate Crosspolymer",
    "Sodium Acryloyl Dimethyl Taurate/PEG-8 Diacrylate Crosspolymer",
    "Sodium DVB/Acrylates Copolymer",
    "Sodium Laneth-40 Maleate/Styrene Sulfonate Copolymer",
    "Sodium MA/Diisobutylene Copolymer",
    "Sodium MA/Vinyl Alcohol Copolymer",
    "Sodium Methacrylate/Styrene Copolymer",
    "Sodium Methoxy PEG-16 Maleate/Styrene Sulfonate Copolymer",
    "Sodium Polyacrylate",
    "Sodium Polyacrylate Starch",
    "Sodium Polymethacrylate",
    "Sodium Polystyrene Sulfonate",
    "Sodium Styrene/Acrylates Copolymer",
    "Sodium Styrene/Acrylates/Divinylbenzene Copolymer",
    "Sodium Styrene/Acrylates/Ethylhexyl Acrylate/Lauryl Acrylate Copolymer",
    "Sodium Styrene/Acrylates/PEG-10 Dimaleate Copolymer",
    "Sodium Styrene/MA Copolymer",
    "Sodium Tauride Acrylates/Acrylic Acid/Acrylonitrogens Copolymer",
    "Starch/Acrylates/Acrylamide Copolymer",
    "Steareth-10 Allyl Ether/Acrylates Copolymer",
    "Stearyl Methacrylate/Perfluorooctylethyl Methacrylate Copolymer",
    "Stearyl/Lauryl Methacrylate Crosspolymer",
    "Stearylvinyl Ether/MA Copolymer",
    "Styrene/Acrylamide Copolymer",
    "Styrene/Acrylates Copolymer",
    "Styrene/Acrylates Copolymer/Polyurethane",
    "Styrene/Acrylates/Acrylonitrile Copolymer",
    "Styrene/Acrylates/Ammonium Methacrylate Copolymer",
    "Styrene/Acrylates/Dimethicone Acrylate Crosspolymer",
    "Styrene/Acrylates/Dimethicone Copolymer",
    "Styrene/Acrylates/Ethylhexyl Acrylate/Lauryl Acrylate Copolymer"
])

red_polymers.extend([
    "Styrene/Butadiene Copolymer",
    "Styrene/MA Copolymer",
    "Styrene/Methacrylamide/Acrylates Copolymer",
    "Styrene/Methylstyrene Copolymer",
    "Styrene/Methylstyrene/Indene Copolymer",
    "Styrene/Stearyl Methacrylate Crosspolymer",
    "Styrene/VA Copolymer",
    "Styrene/VP Copolymer",
    "Sucrose Benzoate/Sucrose Acetate Isobutyrate/Butyl Benzyl Phthalate/Methyl Methacrylate Copolymer",
    "TEA-Acrylates/Ethylhexyl Acrylate Copolymer",
    "TIPA-Acrylates/Ethylhexyl Acrylate Copolymer",
    "Trimethylsiloxysilicate",
    "Trimethylsiloxysilicate/Dimethicone Crosspolymer",
    "Trimethylsiloxysilicate/Dimethiconol Crosspolymer",
    "Tromethamine Acrylates/Acrylonitrogens Copolymer",
    "VA/Butyl Maleate/Isobornyl Acrylate Copolymer",
    "VA/Crotonates/Vinyl Neodecanoate Copolymer",
    "VA/Crotonates/Vinyl Propionate Copolymer",
    "VA/Isobutyl Maleate/Vinyl Neodecanoate Copolymer",
    "VA/Vinyl Butyl Benzoate/Crotonates Copolymer",
    "VA/Vinyl Chloride Copolymer",
    "Vinyl Chloride/Vinyl Laurate Copolymer",
    "Vinyl Dimethicone/Lauryl Dimethicone Crosspolymer",
    "Vinyl Dimethicone/Lauryl/Behenyl Dimethicone Crosspolymer",
    "Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer",
    "Vinyl Dimethyl/Trimethylsiloxysilicate Stearyl Dimethicone Crosspolymer",
    "Vinylamine/Vinyl Alcohol Copolymer",
    "Vinyldimethyl/Trimethylsiloxysilicate Stearyl Dimethicone Crosspolymer",
    "VP/Acrylates/Lauryl Methacrylate Copolymer",
    "VP/Dimethylaminoethylmethacrylate Copolymer",
    "VP/DMAPA Acrylates Copolymer",
    "VP/Methacrylamide/Vinyl Imidazole Copolymer"
])

red_polymers.extend([
    "VP/VA Copolymer",
    "VP/Vinyl Caprolactam/DMAPA Acrylates Copolymer"
])

print(red_polymers, " and ", len(red_polymers))